version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/jin/fastapi-deploy
    overwrite: yes

permissions:
  - object: /home/ubuntu/jin/fastapi-deploy
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
